# Generated by Django 5.2.4 on 2026-05-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='camera_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='has_poe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='recorder_channels',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='catalog_product_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['resolution'], name='catalog_product_res_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['camera_type'], name='catalog_product_cam_type_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['recorder_channels'], name='catalog_product_channels_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['has_poe'], name='catalog_product_poe_idx'),
        ),
    ]
