# Generated by Django 5.2.4 on 2026-05-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_brand_created_by_brand_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='documentation_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='documentation_kk',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='documentation_ru',
            field=models.TextField(blank=True),
        ),
    ]
