services:
  - type: web
    name: hikvision-kz-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && python backend/manage.py collectstatic --noinput && python backend/manage.py migrate
    startCommand: cd backend && gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CORS_ALLOW_CREDENTIALS
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSLMODE
        value: require
      - key: DATABASE_CONN_MAX_AGE
        value: "0"
      - key: MEDIA_ROOT
        value: /var/data/media
      - key: SERVE_MEDIA
        value: "True"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SECURE_PROXY_SSL_HEADER
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "False"
      - key: SECURE_HSTS_PRELOAD
        value: "False"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
    disk:
      name: media
      mountPath: /var/data
      sizeGB: 1
