# Generated by Django 5.2.4 on 2026-05-02 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_kk', models.CharField(max_length=255)),
                ('excerpt_en', models.TextField(blank=True)),
                ('excerpt_ru', models.TextField(blank=True)),
                ('excerpt_kk', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('body_kk', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['slug'], name='blog_post_slug_idx'), models.Index(fields=['is_published', 'published_at'], name='blog_post_published_idx')],
            },
        ),
    ]
