# Generated by Django 5.2.4 on 2026-05-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='bin_or_iin',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
